- name: Create two new GCE instances                                            
  hosts: localhost                                                              
  gather_facts: no                                                              
  vars:                                                                         
    names: www1,www2                                                            
    type: n1-standard-1                                                         
    image: centos-6                                                             
    zone: us-central1-b                                                         
  tasks:                                                                        
    - name: Launch instances                                                    
      local_action: gce instance_names={{ names }} machine_type={{ type }}      
                    image={{ image }} zone={{ zone }}                           
      register: gce                                                             
    - name: Wait for SSH to be available                                        
      local_action: wait_for host={{ item.public_ip }} port=22                  
                    delay=20 timeout=30 state=started                           
      with_items: gce.instance_data